services:
  - type: web
    name: java-compiler
    env: docker
    buildCommand: docker build -t java-compiler .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
    disk:
      name: temp-files
      mountPath: /app/temp
      sizeGB: 1